Repository mswjs/msw, pull requests merged in 2021-02, with the labels that each got.

#577 fix renamed type (OnUnhandledRequest -> UnhandledRequestStrategy)
  src/sharedOptions.ts
Labels: release candidate

#584 Awaits responses in tests by request UUID
  test/support/runBrowserWith.ts
Labels: chore

#583 Skip one-time request handlers inside the response reducer so it handles a scenario with parallel requests
  src/utils/getResponse.ts
  test/msw-api/setup-server/use.test.ts
  test/msw-api/setup-worker/use.test.ts
Labels: release candidate

#598 TypeScript: Fixes declarations auto-import
  .gitignore
  native/package.json
  node/package.json
  package.json
  rollup.config.ts
  tsconfig.json
Labels: release candidate

#612 Exports previously exported types, drops "Type" suffix from types
  src/graphql.ts
  src/handlers/GraphQLHandler.ts
  src/handlers/RequestHandler.ts
  src/handlers/RestHandler.test.ts
  src/handlers/RestHandler.ts
  src/index.ts
  src/rest.ts
  src/utils/internal/parseGraphQLRequest.ts
  src/utils/internal/parseMultipartData.ts
Labels: chore, scope:typescript

#613 Adds tests for "GraphQLHandler" class
  src/handlers/GraphQLHandler.test.ts
  src/handlers/GraphQLHandler.ts
  src/handlers/RequestHandler.ts
  src/utils/internal/parseGraphQLRequest.test.ts
  src/utils/internal/parseGraphQLRequest.ts
Labels: api:graphql

#619 Exports the "RestHandler" class
  src/index.ts
Labels: scope:typescript
