Repository mswjs/msw, pull requests merged in 2021-01, with the labels that each got.

#502 ctx.data: Use "unknown" type instead of "any" type
  src/context/data.ts
Labels: release candidate

#493 Print console message when calling "worker.stop()"
  src/setupWorker/glossary.ts
  src/setupWorker/setupWorker.ts
  src/setupWorker/start/createStart.ts
  src/setupWorker/stop/createStop.ts
  test/msw-api/setup-worker/stop/quiet.mocks.ts
  test/msw-api/setup-worker/stop/quiet.test.ts
Labels: release candidate

#554 Updates project dependencies
  package.json
  yarn.lock
Labels: chore

#565 Retrieves worker client from "ServiceWorkerGlobalScope" instead of "FetchEvent.target"
  src/mockServiceWorker.js
Labels: BREAKING CHANGE

#568 mockServiceWorker: Uses "self" instead of "this"
  src/mockServiceWorker.js
Labels: BREAKING CHANGE, chore, release candidate

#567 Updates project dependencies
  package.json
  yarn.lock
Labels: chore, release candidate

#570 Uses explicit null as 204 response body when handling the "response" worker event
  src/utils/worker/createResponseListener.ts
  test/rest-api/204-response.test.ts
Labels: api:rest, release candidate
