Repository mswjs/msw, pull requests merged in 2021-11, with the labels that each got.

#980 Decode path components in "req.params"
  src/utils/matching/matchRequestUrl.test.ts
  src/utils/matching/matchRequestUrl.ts
  test/rest-api/request/matching/path-params-decode.mocks.ts
  test/rest-api/request/matching/path-params-decode.node.test.ts
  test/rest-api/request/matching/path-params-decode.test.ts
Labels: release candidate

#989 deps: update "fs-teardown" to 0.3.0
  package.json
  test/msw-api/auto-update-worker.test.ts
  test/msw-api/cli/init.test.ts
  test/msw-api/setup-worker/fallback-mode/fallback-mode.test.ts
  test/support/utils.ts
  yarn.lock
Labels: chore

#999 fix(RestHandler): set default "req.params" to ambiguous type
  src/handlers/RestHandler.ts
  src/index.ts
  src/rest.ts
  src/utils/matching/matchRequestUrl.ts
  test/msw-api/setup-server/scenarios/generator.node.test.ts
  test/rest-api/params.mocks.ts
  test/typings/rest.test-d.ts
Labels: scope:typescript, DX

#994 feat: export Worker and Server api options type
  src/index.ts
  src/node/createSetupServer.ts
  src/node/index.ts
  src/setupWorker/glossary.ts
  src/setupWorker/start/utils/prepareStartHandler.test.ts
  src/setupWorker/start/utils/prepareStartHandler.ts
  src/sharedOptions.ts
  src/typeUtils.ts
  src/utils/handleRequest.test.ts
  src/utils/handleRequest.ts
  src/utils/worker/createFallbackRequestListener.ts
  src/utils/worker/createRequestListener.ts
Labels: scope:typescript, DX
