Repository mswjs/msw, pull requests merged in 2024-01, with the labels that each got.

#1874 fix: support typescript@5.3
  .github/workflows/compat.yml
  package.json
  test/typings/tsconfig.5.3.json
Labels: release candidate, scope:typescript

#1914 fix: cache request cloning and request parsing
  .nvmrc
  src/core/handlers/GraphQLHandler.ts
  src/core/handlers/RequestHandler.ts
  src/node/SetupServerApi.ts
  src/node/setupServer.ts
  test/node/regressions/many-request-handlers-jsdom.test.ts
  test/node/regressions/many-request-handlers.test.ts
  test/node/vitest.config.ts
Labels: release candidate, performance

#1957 fix(GraphQLHandler): move cookie parsing to parse phase
  src/core/handlers/GraphQLHandler.test.ts
  src/core/handlers/GraphQLHandler.ts
Labels: release candidate

#1912 ci: nightly rc check for typescript
  .github/workflows/typescript-nightly.yml
Labels: chore

#1963 feat: support throwing responses in response resolvers
  src/core/handlers/RequestHandler.ts
  test/browser/rest-api/response/response-error.test.ts
  test/browser/rest-api/response/throw-response.mocks.ts
  test/browser/rest-api/response/throw-response.test.ts
  test/node/rest-api/response/throw-response.node.test.ts
Labels: release candidate

#1964 feat: deprecate "waitUntilReady" (deferNetworkUntil) worker option
  src/browser/setupWorker/setupWorker.ts
  src/browser/setupWorker/start/createStartHandler.ts
  test/browser/msw-api/setup-worker/start/wait-until-ready.error.mocks.ts
  test/browser/msw-api/setup-worker/start/wait-until-ready.error.test.ts
  test/browser/msw-api/setup-worker/start/wait-until-ready.false.mocks.ts
  test/browser/msw-api/setup-worker/start/wait-until-ready.mocks.ts
  test/browser/msw-api/setup-worker/start/wait-until-ready.test.ts
  test/browser/msw-api/setup-worker/start/warn-on-wait-until-ready.mocks.ts
  test/browser/msw-api/setup-worker/start/warn-on-wait-until-ready.test.ts
Labels: release candidate

#1832 feat: support multiple directories in "msw.workerDirectory"
  cli/index.js
  cli/init.js
  config/scripts/postinstall.js
  test/node/msw-api/auto-update-worker.node.test.ts
  test/node/msw-api/cli/init.node.test.ts
  test/support/utils.ts
Labels: release candidate

#1942 feat: add "requestId" as response resolver argument
  src/core/handlers/RequestHandler.ts
  src/core/utils/getResponse.ts
  src/core/utils/handleRequest.test.ts
  src/core/utils/handleRequest.ts
Labels: release candidate

#1966 chore: upgrade dependencies
  .github/workflows/ci.yml
  .github/workflows/compat.yml
  .gitignore
  babel.config.js
  package-lock.json
  package.json
  pnpm-lock.yaml
  test/node/graphql-api/compatibility.node.test.ts
Labels: release candidate, chore

#1780 feat: up tsconfig target for more modern syntax
  .github/workflows/smoke-test.yml
  tsconfig.base.json
Labels: release candidate

#1982 fix: export "getResponse" for batched GraphQL queries
  src/core/getResponse.test.ts
  src/core/getResponse.ts
  src/core/handlers/GraphQLHandler.test.ts
  src/core/handlers/HttpHandler.test.ts
  src/core/handlers/HttpHandler.ts
  src/core/handlers/RequestHandler.ts
  src/core/index.ts
  src/core/utils/executeHandlers.ts
  src/core/utils/handleRequest.test.ts
  src/core/utils/handleRequest.ts
  src/core/utils/internal/randomId.ts
  test/node/graphql-api/batched-queries.apollo.test.ts
  test/node/graphql-api/batched-queries.batched-execute.test.ts
Labels: release candidate, api:graphql

#1988 fix: bundle browser build
  tsup.config.ts
Labels: DX, chore, performance

#1997 fix: does not warn on unhandled "file://" requests
  src/core/handlers/GraphQLHandler.ts
  src/core/handlers/HttpHandler.ts
  src/core/utils/internal/parseGraphQLRequest.ts
  src/core/utils/request/getPublicUrlFromRequest.test.ts
  src/core/utils/request/getPublicUrlFromRequest.ts
  src/core/utils/request/onUnhandledRequest.ts
  src/core/utils/request/toPublicUrl.test.ts
  src/core/utils/request/toPublicUrl.ts
  test/node/msw-api/setup-server/scenarios/on-unhandled-request/callback.node.test.ts
  test/node/msw-api/setup-server/scenarios/on-unhandled-request/default.node.test.ts
Labels: release candidate
