Repository mswjs/msw, pull requests merged in 2024-02, with the labels that each got.

#2002 fix: return type of "passthrough"
  src/core/passthrough.ts
  test/typings/graphql.test-d.ts
  test/typings/http.test-d.ts
Labels: release candidate, scope:typescript, DX

#2016 fix: improve fetch compatibility with React Native
  package.json
  pnpm-lock.yaml
Labels: release candidate, scope:react-native

#2017 fix: support intercepting fetch requests in React Native
  src/native/index.ts
Labels: release candidate, scope:react-native

#2000 feat: support concurrent test runs via "server.boundary"
  package.json
  src/browser/setupWorker/glossary.ts
  src/browser/setupWorker/setupWorker.ts
  src/browser/setupWorker/start/createFallbackRequestListener.ts
  src/browser/setupWorker/start/createRequestListener.ts
  src/core/SetupApi.ts
  src/native/index.ts
  src/node/SetupServerApi.ts
  src/node/SetupServerCommonApi.ts
  src/node/glossary.ts
  src/node/setupServer.ts
  test/node/msw-api/setup-server/boundary/boundary.args.test.ts
  test/node/msw-api/setup-server/boundary/boundary.concurrency.test.ts
  test/node/msw-api/setup-server/boundary/boundary.handlers.test.ts
  test/node/msw-api/setup-server/life-cycle-events/on.node.test.ts
Labels: release candidate

#1996 feat: automatically set "Content-Length" on text/json responses
  src/core/HttpResponse.test.ts
  src/core/HttpResponse.ts
  test/node/rest-api/response/body-json.node.test.ts
  test/node/rest-api/response/body-text.node.test.ts
Labels: release candidate

#2004 feat: add "/http" and "/graphql" export paths
  package.json
Labels: release candidate

#2021 feat: drop webpack 4 support (remove "chokidar")
  package.json
  pnpm-lock.yaml
Labels: release candidate

#2031 fix(setupWorker): set "response.url" in "response:*" events
  src/browser/setupWorker/start/createResponseListener.ts
  test/browser/msw-api/setup-worker/life-cycle-events/on.mocks.ts
  test/browser/msw-api/setup-worker/life-cycle-events/on.test.ts
Labels: release candidate

#2043 fix: remove unused types
  src/browser/setupWorker/glossary.ts
Labels: chore
