Repository mswjs/msw, pull requests merged in 2024-12, with the labels that each got.

#2211 chore: update pnpm to v9.14.0
  .github/workflows/ci.yml
  .github/workflows/compat.yml
  .github/workflows/release.yml
  .github/workflows/smoke-test.yml
  .github/workflows/typescript-nightly.yml
  package.json
  pnpm-lock.yaml
  test/browser/msw-api/setup-worker/start/start.test.ts
  test/browser/rest-api/request/body/body-form-data.test.ts
  test/browser/rest-api/request/body/body-json.test.ts
  test/browser/ws-api/ws.clients.browser.test.ts
  test/browser/ws-api/ws.use.browser.test.ts
Labels: chore

#2375 fix(setupWorker): correctly delete internal `accept` header on passthrough
  src/mockServiceWorker.js
  test/browser/msw-api/setup-worker/worker-passthrough-header.mocks.ts
  test/browser/msw-api/setup-worker/worker-passthrough-header.test.ts
Labels: release candidate, scope:browser

#2383 fix(setupServer): reapply interception after calling `server.listen()` after `server.close()`
  src/node/SetupServerCommonApi.ts
  test/node/regressions/2370-listen-after-close.test.ts
Labels: release candidate

#2389 fix: support `SharedArrayBuffer` in `HttpResponse.arrayBuffer`
  src/core/HttpResponse.test.ts
  src/core/HttpResponse.ts
Labels: release candidate
